import { FC } from 'react';
import Head from 'next/head';
import styles from './layout.module.css';

export const Layout: FC = ({ children }) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Marc Weinberger - Software Engineer</title>
          <meta name="author" content="Marc Weinberger" />
          <meta name="description" content="Generated by create next app" />
          <meta
            name="keywords"
            content="portfolio Marc Weinberger freelance software kotlin backend kafka spring react"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>{children}</main>

        <footer className={styles.footer} />
      </div>
    </>
  );
};
